export const books = [
    {
        id: 1,
        bookTitle: 'Silver Tears',
        bookPrice: '$75',
        bookOldPrice: '$130',
        bookAuthor: 'Danny James',
        pageCount: '400',
        isbn: '132123',
        isNew: true,
        isOnSale: false,
        bookDescription: 'I recently picked up a nonfiction book, which I don’t read many of, and almost put it right back down. But the description intrigued me. It got me to read the first couple pages, standing right there in the store. Then it got me to buy the book. A book description is one of the most crucial elements to selling your book (if not the crucial element), and yet it’s often the hardest thing for writers to come up with.',
        imageUrl: 'http://www.giovaniimoveis.com.br/app/webroot/template/revolution/assets/demo/magazine-posts/c2fe7-book-cover.jpg'
    },
    {
        id: 2,
        bookTitle: 'A Killer Product Demo',
        bookPrice: '$320',
        bookOldPrice: '$500',
        bookAuthor: 'Danny James',
        pageCount: '470',
        isbn: '132123',
        isNew: false,
        isOnSale: true,
        bookDescription: 'I recently picked up a nonfiction book, which I don’t read many of, and almost put it right back down. But the description intrigued me. It got me to read the first couple pages, standing right there in the store. Then it got me to buy the book. A book description is one of the most crucial elements to selling your book (if not the crucial element), and yet it’s often the hardest thing for writers to come up with.',
        imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/513Pefzt5XL._SX321_BO1,204,203,200_.jpg'
    },
    {
        id: 3,
        bookTitle: 'The Journey To The Past',
        bookPrice: '$210',
        bookOldPrice: '$350',
        bookAuthor: 'Danny James',
        pageCount: '540',
        isbn: '132123',
        isNew: false,
        isOnSale: false,
        bookDescription: 'I recently picked up a nonfiction book, which I don’t read many of, and almost put it right back down. But the description intrigued me. It got me to read the first couple pages, standing right there in the store. Then it got me to buy the book. A book description is one of the most crucial elements to selling your book (if not the crucial element), and yet it’s often the hardest thing for writers to come up with.',
        imageUrl: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/book-cover-design-template-9cbed64fb4818ea7ee80297730d31042_screen.jpg?ts=1567014278'
    },
    {
        id: 4,
        bookTitle: 'The Smith Poems',
        bookPrice: '$50',
        bookOldPrice: '$100',
        bookAuthor: 'Danny James',
        pageCount: '400',
        isbn: '132123',
        isNew: false,
        isOnSale: false,
        bookDescription: 'I recently picked up a nonfiction book, which I don’t read many of, and almost put it right back down. But the description intrigued me. It got me to read the first couple pages, standing right there in the store. Then it got me to buy the book. A book description is one of the most crucial elements to selling your book (if not the crucial element), and yet it’s often the hardest thing for writers to come up with.',
        imageUrl: 'https://m.media-amazon.com/images/I/41YfngsPoxL.SX316.SY316.jpg'
    },
    {
        id: 5,
        bookTitle: 'Nora Barrett',
        bookPrice: '$50',
        bookOldPrice: '$100',
        bookAuthor: 'Danny James',
        pageCount: '400',
        isbn: '132123',
        isNew: true,
        isOnSale: false,
        bookDescription: 'I recently picked up a nonfiction book, which I don’t read many of, and almost put it right back down. But the description intrigued me. It got me to read the first couple pages, standing right there in the store. Then it got me to buy the book. A book description is one of the most crucial elements to selling your book (if not the crucial element), and yet it’s often the hardest thing for writers to come up with.',
        imageUrl: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/action-thriller-book-cover-design-template-3675ae3e3ac7ee095fc793ab61b812cc_screen.jpg?ts=1588152105'
    },
    {
        id: 6,
        bookTitle: 'The Arrivals',
        bookPrice: '$50',
        bookOldPrice: '$100',
        bookAuthor: 'Danny James',
        pageCount: '400',
        isbn: '132123',
        isNew: true,
        isOnSale: true,
        bookDescription: 'I recently picked up a nonfiction book, which I don’t read many of, and almost put it right back down. But the description intrigued me. It got me to read the first couple pages, standing right there in the store. Then it got me to buy the book. A book description is one of the most crucial elements to selling your book (if not the crucial element), and yet it’s often the hardest thing for writers to come up with.',
        imageUrl: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/sci-fi-book-cover-template-a1ec26573b7a71617c38ffc6e356eef9_screen.jpg?ts=1561547637'
    },
    {
        id: 7,
        bookTitle: 'The Invasion Of Zombie Alliens',
        bookPrice: '$50',
        bookOldPrice: '$100',
        bookAuthor: 'Danny James',
        pageCount: '400',
        isbn: '132123',
        isNew: false,
        isOnSale: true,
        bookDescription: 'I recently picked up a nonfiction book, which I don’t read many of, and almost put it right back down. But the description intrigued me. It got me to read the first couple pages, standing right there in the store. Then it got me to buy the book. A book description is one of the most crucial elements to selling your book (if not the crucial element), and yet it’s often the hardest thing for writers to come up with.',
        imageUrl: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/sci-fi-kindle-book-cover-design-template-bd12cf83a9f9d72327e372c5db1d2883_screen.jpg?ts=1561443942'
    },
    {
        id: 8,
        bookTitle: 'Murder In A Mountain Hut',
        bookPrice: '$50',
        bookOldPrice: '$100',
        bookAuthor: 'Danny James',
        pageCount: '400',
        isbn: '132123',
        isNew: true,
        isOnSale: true,
        bookDescription: 'I recently picked up a nonfiction book, which I don’t read many of, and almost put it right back down. But the description intrigued me. It got me to read the first couple pages, standing right there in the store. Then it got me to buy the book. A book description is one of the most crucial elements to selling your book (if not the crucial element), and yet it’s often the hardest thing for writers to come up with.',
        imageUrl: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/murder-mystery-book-cover-design-template-2a1a3ff53d7a9d851046c5e1fdf3943f_screen.jpg?ts=1588152105'
    },
    {
        id: 9,
        bookTitle: 'The Truth',
        bookPrice: '$50',
        bookOldPrice: '$100',
        bookAuthor: 'Danny James',
        pageCount: '400',
        isbn: '132123',
        isNew: false,
        isOnSale: false,
        bookDescription: 'I recently picked up a nonfiction book, which I don’t read many of, and almost put it right back down. But the description intrigued me. It got me to read the first couple pages, standing right there in the store. Then it got me to buy the book. A book description is one of the most crucial elements to selling your book (if not the crucial element), and yet it’s often the hardest thing for writers to come up with.',
        imageUrl: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/book-cover-template-design-cbaded1d46f6d152f77b911783007df8_screen.jpg?ts=1573018413'
    },
    {
        id: 10,
        bookTitle: 'Creative Ideas',
        bookPrice: '$50',
        bookOldPrice: '$100',
        bookAuthor: 'Danny James',
        pageCount: '400',
        isbn: '132123',
        isNew: false,
        isOnSale: false,
        bookDescription: 'I recently picked up a nonfiction book, which I don’t read many of, and almost put it right back down. But the description intrigued me. It got me to read the first couple pages, standing right there in the store. Then it got me to buy the book. A book description is one of the most crucial elements to selling your book (if not the crucial element), and yet it’s often the hardest thing for writers to come up with.',
        imageUrl: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/how-to-creative-ideas-book-cover-design-template-52f7ec58f53452b9b46a351cea1bd9a1_screen.jpg?ts=1568463645'
    },
    {
        id: 11,
        bookTitle: 'Story Of Little Regina',
        bookPrice: '$50',
        bookOldPrice: '$100',
        bookAuthor: 'Danny James',
        pageCount: '400',
        isbn: '132123',
        isNew: false,
        isOnSale: true,
        bookDescription: 'I recently picked up a nonfiction book, which I don’t read many of, and almost put it right back down. But the description intrigued me. It got me to read the first couple pages, standing right there in the store. Then it got me to buy the book. A book description is one of the most crucial elements to selling your book (if not the crucial element), and yet it’s often the hardest thing for writers to come up with.',
        imageUrl: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/street-homeless-girl-book-cover-design-template-07f7b404f6551e172d13d6e4a48ed9b0_screen.jpg?ts=1591611205'
    },
    {
        id: 12,
        bookTitle: 'Affiliate Marketing',
        bookPrice: '$50',
        bookOldPrice: '$100',
        bookAuthor: 'Danny James',
        pageCount: '400',
        isbn: '132123',
        isNew: false,
        isOnSale: true,
        bookDescription: 'I recently picked up a nonfiction book, which I don’t read many of, and almost put it right back down. But the description intrigued me. It got me to read the first couple pages, standing right there in the store. Then it got me to buy the book. A book description is one of the most crucial elements to selling your book (if not the crucial element), and yet it’s often the hardest thing for writers to come up with.',
        imageUrl: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/affiliate-marketing-kindle-book-cover-design-template-921b2bda022dd8ce155740dcff958c33_screen.jpg?ts=1561416772'
    },
    {
        id: 13,
        bookTitle: 'House Of Secrets',
        bookPrice: '$50',
        bookOldPrice: '$100',
        bookAuthor: 'Danny James',
        pageCount: '400',
        isbn: '132123',
        isNew: false,
        isOnSale: false,
        bookDescription: 'I recently picked up a nonfiction book, which I don’t read many of, and almost put it right back down. But the description intrigued me. It got me to read the first couple pages, standing right there in the store. Then it got me to buy the book. A book description is one of the most crucial elements to selling your book (if not the crucial element), and yet it’s often the hardest thing for writers to come up with.',
        imageUrl: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/haunted-house-horror-book-cover-design-template-fd3a8016a4128af962549c3c40190270_screen.jpg?ts=1588747771'
    },
    {
        id: 14,
        bookTitle: 'Common Plants',
        bookPrice: '$50',
        bookOldPrice: '$150',
        bookAuthor: 'Saggy Denial',
        pageCount: '250',
        isbn: '132123',
        isNew: false,
        isOnSale: false,
        bookDescription: 'I recently picked up a nonfiction book, which I don’t read many of, and almost put it right back down. But the description intrigued me. It got me to read the first couple pages, standing right there in the store. Then it got me to buy the book. A book description is one of the most crucial elements to selling your book (if not the crucial element), and yet it’s often the hardest thing for writers to come up with.',
        imageUrl: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/plants-book-cover-design-template-8dde9e21eb04e35d4a5ab0cc6e5a48a5_screen.jpg?ts=1561539379'
    },
    {
        id: 15,
        bookTitle: 'Mastermind',
        bookPrice: '$50',
        bookOldPrice: '$100',
        bookAuthor: 'Danny James',
        pageCount: '400',
        isbn: '132123',
        isNew: false,
        isOnSale: false,
        bookDescription: 'I recently picked up a nonfiction book, which I don’t read many of, and almost put it right back down. But the description intrigued me. It got me to read the first couple pages, standing right there in the store. Then it got me to buy the book. A book description is one of the most crucial elements to selling your book (if not the crucial element), and yet it’s often the hardest thing for writers to come up with.',
        imageUrl: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/thriller-suspense-book-cover-design-template-1438d47348d378a3f26d2c78a2b48a54_screen.jpg?ts=1588747772'
    },
    {
        id: 16,
        bookTitle: 'Dark Summer Nights',
        bookPrice: '$150',
        bookOldPrice: '$200',
        bookAuthor: 'Rocky Dan',
        pageCount: '370',
        isbn: '132123',
        isNew: true,
        isOnSale: true,
        bookDescription: 'I recently picked up a nonfiction book, which I don’t read many of, and almost put it right back down. But the description intrigued me. It got me to read the first couple pages, standing right there in the store. Then it got me to buy the book. A book description is one of the most crucial elements to selling your book (if not the crucial element), and yet it’s often the hardest thing for writers to come up with.',
        imageUrl: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/purple-mystery-story-book-cover-design-template-2fa5ce221a30be6cc31065eb36a0aab3_screen.jpg?ts=1588747771'
    },
    {
        id: 17,
        bookTitle: 'Key Hole Of The Truth',
        bookPrice: '$500',
        bookOldPrice: '$1500',
        bookAuthor: 'John Michel',
        pageCount: '400',
        isbn: '132123',
        isNew: true,
        isOnSale: true,
        bookDescription: 'I recently picked up a nonfiction book, which I don’t read many of, and almost put it right back down. But the description intrigued me. It got me to read the first couple pages, standing right there in the store. Then it got me to buy the book. A book description is one of the most crucial elements to selling your book (if not the crucial element), and yet it’s often the hardest thing for writers to come up with.',
        imageUrl: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/thriller-adventure-book-cover-design-template-f679760b6a4b518c724487de1c312746_screen.jpg?ts=1588747775'
    },
    {
        id: 18,
        bookTitle: 'Catch-22',
        bookPrice: '$530',
        bookOldPrice: '$1100',
        bookAuthor: 'Danny James',
        pageCount: '500',
        isbn: '132123',
        isNew: true,
        isOnSale: false,
        bookDescription: 'I recently picked up a nonfiction book, which I don’t read many of, and almost put it right back down. But the description intrigued me. It got me to read the first couple pages, standing right there in the store. Then it got me to buy the book. A book description is one of the most crucial elements to selling your book (if not the crucial element), and yet it’s often the hardest thing for writers to come up with.',
        imageUrl: 'https://static.independent.co.uk/s3fs-public/thumbnails/image/2014/03/11/16/catch-22.jpg'
    },
    {
        id: 19,
        bookTitle: 'Suheldev - The King Who Saved India',
        bookPrice: '$350',
        bookOldPrice: '$600',
        bookAuthor: 'David Hussey',
        pageCount: '800',
        isbn: '132123',
        isNew: true,
        isOnSale: false,
        bookDescription: 'I recently picked up a nonfiction book, which I don’t read many of, and almost put it right back down. But the description intrigued me. It got me to read the first couple pages, standing right there in the store. Then it got me to buy the book. A book description is one of the most crucial elements to selling your book (if not the crucial element), and yet it’s often the hardest thing for writers to come up with.',
        imageUrl: 'https://images-eu.ssl-images-amazon.com/images/I/51UNiQJBLEL._AC_SX368_.jpg'
    },
    {
        id: 20,
        bookTitle: 'Henna Artist',
        bookPrice: '$50',
        bookOldPrice: '$100',
        bookAuthor: 'Danny James',
        pageCount: '400',
        isbn: '132123',
        isNew: true,
        isOnSale: true,
        bookDescription: 'I recently picked up a nonfiction book, which I don’t read many of, and almost put it right back down. But the description intrigued me. It got me to read the first couple pages, standing right there in the store. Then it got me to buy the book. A book description is one of the most crucial elements to selling your book (if not the crucial element), and yet it’s often the hardest thing for writers to come up with.',
        imageUrl: 'https://images-eu.ssl-images-amazon.com/images/I/51WD9NZ45uL._AC_SX368_.jpg'
    },
]

export const MockBookDetail = (id: number) => {
    const bookDetail = books.find(book => book.id === Number(id))
    return bookDetail;
}